### PR TITLE
Specify python_requires to prevent installation on Python 3

### PR DESCRIPTION
**Pull request by eli-schwartz**
Rather than merely being pointless to install on Python 3, this package
will actually cause syntax errors on Python 3.

This is a problem as installing it anyway will shadow the version in
the stdlib.

### CODE REVIEW

**Comment by agronholm** [comment]
It won't shadow it because stdlib imports cannot be overridden, unless very explicit measures are taken.

**Comment by agronholm** [comment]
Don't drop the condition in `setup.py`. Do that and I'll merge.
Though I can't help but to wonder how many projects will break because of this given that the download statistics show over 300k installs on Python 3.6 for this project, meaning it is an unconditional dependency for a lot of projects.

**Comment by eli-schwartz** [comment]
Well, apparently I should not be doing this late at night. :D Naturally, '' will override the stdlib, and byte-compiling it provides an awkward error message from setuptools (that pip -v might even show).

Still as a matter of technical correctness this should be done. And it would head off bugs like [this](https://bugs.archlinux.org/task/56041) at the pass, since distros quite naturally do not package futures for python3 and projects should fix themselves.

force-pushed; the warning is useful anyway I guess, for manual clone + install via `python3 setup.py install` (pip will suppress it unless you escalate to an error).

**Comment by agronholm** [comment]
Thanks.

**Pull request merged**
