### PR TITLE
Backport py3 exit

### PR DESCRIPTION
**Pull request by mpacer**
I would prefer to  make this against a 3.1x backport branch, but I'll make it against master since that's the closest I can.

As of today if I am in a python 3 environment and I install futures, 3.1.1 is installed:

```
(broken_python3) ~ $ pip3 install futures
Collecting futures
  Downloading https://files.pythonhosted.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz
Building wheels for collected packages: futures
  Running setup.py bdist_wheel for futures ... done
  Stored in directory: /Users/mpacer/Library/Caches/pip/wheels/f3/f9/c7/4fbf1faa6038faf183f6e3ea61f17a5f7eea5ab9a1dd7753fd
Successfully built futures
Installing collected packages: futures
Successfully installed futures-3.1.1
```

Unfortunately, this will still occur even after you release the next 3.2 version because pip3 will never download any version of futures that includes `"python_requires>=2.6, <3.0"`. It will continue to download 3.1.1 — which will break anyone's python3 concurrent.futures packages.

I don't think that you should leave out `python_requires` for any other versions of the package. There just needs to be some version of `futures` > 3.1.1 (e.g., 3.1.2) that has this explicit catch and exit.

### CODE REVIEW

**Comment by mpacer** [comment]
Note: this branches off from 65552e4ae925451679ed9b8d40c0971366abc718 (your git tag for 3.1.1)

**Comment by agronholm** [comment]
As you made this PR against my master branch, I cannot merge it as-is. If all else fails, I'll just change the files locally and make the 3.1.2 release directly.

**Comment by agronholm** [comment]
Just help understand how this fixes anything. If pip is new enough to understand `python_requires`, it will most certainly install the wheel, in which case the setup.py code is not run anyway.

**Comment by agronholm** [comment]
Unless I explicitly opt not to publish a wheel for 3.1.2?

**Comment by agronholm** [comment]
I published a 3.1.2 as a tarball but pip will still install 3.1.1 instead of that. Now what?

**Comment by agronholm** [comment]
I closed this PR because I did it myself but if you have other ideas, feel free to share.

**Pull request closed without merging**
