### PR TITLE
Add process initializer (from Python 3.7) to complete issue 21423 implementation

### PR DESCRIPTION
**Pull request by fahhem**
Also updates the docs for thread and process pools.

Unfortunately, the ProcessPoolExecutor is vastly differently implemented than upstream Python 3, so I couldn't use stick to the upstream PR as much as for thread pools: https://github.com/python/cpython/pull/4241/files

Is there any interest in wholesale copying the Python 3.7 process pool executor instead of redoing the bpo's out of order?

### CODE REVIEW

**Comment by s0undt3ch** [comment]
After merge what would be the expected time frame to release it?

**Comment by agronholm** [comment]
> Also updates the docs for thread and process pools.

But, there should also be new tests. Surely Python 3 had some added when this feature was introduced?

> Is there any interest in wholesale copying the Python 3.7 process pool executor instead of redoing the bpo's out of order?

IIRC the new process pool executor relies on Python 3 features. Otherwise would've been nice because process pools are broken beyond repair on Python 2.

> After merge what would be the expected time frame to release it?

Within a day or two. It should be noted that since Python 2 has now reached its End Of Life, I will not be adding any more features to this library beyond this one. If somebody else wants to take over, that is negotiable.

**Comment by fahhem** [comment]
Seeing as I never got around to this and I don't work anywhere that uses Python 2 anymore, I'm going to close this PR. Good luck to anyone who needs this!

**Comment by agronholm** [comment]
Yeah, nobody should be using this anymore.

**Pull request closed without merging**
