### PR TITLE
Create better error info in the case that PY3 was installed

### LINKED ISSUE #78: Issue: __get_result incorrectly overwrites the correct version when installed on python 3.
https://github.com/agronholm/pythonfutures/blob/5edbc65401fd578e195c2f0e2e8d3a6b5404f6bc/concurrent/futures/_base.py#L405-L416

I'm happy to make a PR to fix this, but I think the real solution is to release a new version that does not include the `python_requires='>=2.6, <3',`  and raises an error instead of a warning when attempted to be installed on python 3. 

For example, the monkey patching will break `pytest` if installed on `python3` with version `3.1.1`. That means if someone does `pip3 install -U futures`, that `python3` executable would install a `futures==3.1.1` because it doesn't have a `python_requires='>=2.6, <3',` which is what stops `pip3` from even seeing that `futures 3.2.0` exists. 

If we were to raise an error in a way analogous to what we do in IPython:
https://github.com/ipython/ipython/blob/01bd59ec7c184171df0cb0d933c5672e8c20b67e/setup.py#L25-L58:
```python
if sys.version_info < (3, 4):
    pip_message = 'This may be due to an out of date pip. Make sure you have pip >= 9.0.1.'
    try:
        import pip
        pip_version = tuple([int(x) for x in pip.__version__.split('.')[:3]])
        if pip_version < (9, 0, 1) :
            pip_message = 'Your pip version is out of date, please install pip >= 9.0.1. '\
            'pip {} detected.'.format(pip.__version__)
        else:
            # pip is new enough - it must be something else
            pip_message = ''
    except Exception:
        pass


    error = """
IPython 7.0+ supports Python 3.4 and above.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 was supported up to IPython 6.x.
See IPython `README.rst` file for more information:
    https://github.com/ipython/ipython/blob/master/README.rst
Python {py} detected.
{pip}
""".format(py=sys.version_info, pip=pip_message )

    print(error, file=sys.stderr)
    sys.exit(1)
```
then `pip install -U futures` would successfully avoid breaking peoples' `python3` executables by not allowing itself to be installed. I'll happiliy make a PR for this.

### PR DESCRIPTION
**Pull request by mpacer**
This closes #78. There is more context in that issue.

The crux of the issue is that installing this library on Python 3 breaks Python 3's `__get_result` method. This breaks `pytest`. 

This is particularly problematic if you are relying on a library that itself has not updated their dependencies to have the newer `'futures; python_version == "2.7"'` dependency specifier in the `install_requires`. 

In general, it is better to stop people from installing something if doing so will break a common testing framework.

That means we need to provide an error to let people know why it didn't work. 

At the same time, it also tells library writers to where to go to learn how to change their `install_requires` in `setuptools.setup` for when their users run into the error & copy and paste it into issues.

### CODE REVIEW

**Comment by agronholm** [comment]
You do realize that with these changes, there is nothing in the resulting wheel that will prevent py3 users from installing it? When installing the wheel, setup.py is not touched.

**Comment by mpacer** [comment]
Yes, we also need to make a change to the `__init__.py`. The wheel install would count as an alternate case where `setup.py` isn’t touched but the package is installed. 

We cover that for the case of editable installs that then are `git pull`ed from upstream in the talk, but this specific case is analogous([discussed 18 mins into the talk](https://youtu.be/2DkfPzWWC2Q?t=18m39s)).

**Comment by mpacer** [comment]
Alternatively we could modify the setup.cfg to have either of the following:

```
[bdist_wheel]
python-tag = py2
```
 Or
```
[bdist_wheel]
universal = 0
```

Setting python-tag directly is cleaner, but universal would work since you would then need to build the wheel with python2 since the `setup.py` would be run blocking building on python3.

**Comment by agronholm** [comment]
What you're suggesting in setup.cfg is actually the default. As you can see from the [PyPI](https://pypi.org/project/futures/#files), I'm already producing Python 2 only wheels. Now that I've given more thought to the matter, I believe that the proper solution is to hard fail when running `setup.py` on Python 3 instead of giving a warning since the code is no longer syntax compatible.

**Comment by mpacer** [comment]
The one additional step needed is to release a version of this setup.py that will be installed if people try to install `futures` in Python 3. Because otherwise it'll install `futures` version `3.1.1` instead of failing.

**Comment by mpacer** [comment]
I'll make a new pull request to make a smaller set of changes.

**Comment by mpacer** [comment]
I created #81 to address the backport issue.

**Pull request closed without merging**
