### PR TITLE
Make Future.__repr__ subclass-friendly and minor doc typos

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by agronholm** [comment]
Is this change coming from upstream?

**Comment by dalcinl** [comment]
Sorry, forgot to mention https://bugs.python.org/issue22033. Do you want me to edit the commit message?

**Comment by agronholm** [comment]
Yes, please mention this in the commit message. I will look at this PR later today.

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
